# Artificial Neural Network - Solving Classification Problems

Artificial Neural Networks(ANN) are part of supervised machine learning where we will be having input as well as corresponding output present in our dataset. Our whole aim is to figure out a way of mapping this input to the respective output. ANN can be used for solving both regression and classification problems.

**1. Importing the required libraries**

In [20]:
import pandas as pd
import numpy as np
import tensorflow as tf

**2. Importing the Data set**

In [21]:
bank_df = pd.read_csv('bank.csv', delimiter=';')

In [22]:
bank_df.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

In [23]:
# We have a dataset where we are having 17 dimensions in total and 4521 record
bank_df.shape

(4521, 17)

* Here our main goal is to create an artificial neural network that will take into consideration all independent variables(first 16) and based on that will predict if our customer is going to exit the bank or not(Exited is dependent variable here).

**4. Generating Matrix of Features for X (Independent variables)**

In [24]:
X = bank_df.iloc[:, 0:-1].values

In [25]:
X

array([[30, 'unemployed', 'married', ..., -1, 0, 'unknown'],
       [33, 'services', 'married', ..., 339, 4, 'failure'],
       [35, 'management', 'single', ..., 330, 1, 'failure'],
       ...,
       [57, 'technician', 'married', ..., -1, 0, 'unknown'],
       [28, 'blue-collar', 'married', ..., 211, 3, 'other'],
       [44, 'entrepreneur', 'single', ..., 249, 7, 'other']], dtype=object)

**5. Generating Dependent Variable Vector (Y)**

In [26]:
Y = bank_df.iloc[:, -1].values

In [27]:
Y

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

* Feature engineering is a phase where we either generate new variables from existing ones or modify existing variables so as to use them in our machine learning model. We need to convert those string values into their numerical equivalent without losing their significance using Encoding.

**6. Use Label Encoding for categorical variable(Y) to yes and no or 1 and 0**

In [28]:
#encoding output variable y: subscribed or not
from sklearn.preprocessing import LabelEncoder

In [29]:
LE1 = LabelEncoder()
Y = np.array(LE1.fit_transform(Y))

In [30]:
Y

array([0, 0, 0, ..., 0, 0, 0])

**7. Use Label Encoding for features/categorical variable(X)**

In [31]:
#using label encoder for marital status, default, housing, loan, contact and poutcomme
X[:,2] = np.array(LE1.fit_transform(X[:,2]))
X[:,4] = np.array(LE1.fit_transform(X[:,4]))
X[:,6] = np.array(LE1.fit_transform(X[:,6]))
X[:,7] = np.array(LE1.fit_transform(X[:,7]))
X[:,8] = np.array(LE1.fit_transform(X[:,8]))
X[:,15] = np.array(LE1.fit_transform(X[:,15]))

In [32]:
X[0]

array([30, 'unemployed', 1, 'primary', 0, 1787, 0, 0, 0, 19, 'oct', 79, 1,
       -1, 0, 3], dtype=object)

**8. Using One Hot Encoding to convert job, education and month so that machine learning does not assume higher number is important. Using column Transformer to pick a particular column**

In [33]:
from sklearn.compose import ColumnTransformer

In [43]:
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder="passthrough")
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[14])], remainder="passthrough")
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[24])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [44]:
X[0]

array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 30, 1, 0, 1787, 0, 0, 0, 19, 79, 1, -1, 0, 3],
      dtype=object)

**9. Splitting dataset into train test**

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

**10. Perform Feature Scaling**

* Feature scaling: sometimes certain variables can have high values and some low, without scaling the high value variable can dominate and low value variable may be neglected, so feature scaling is done.

* Feature scaling before or after split: should be done after splitting into train and test sets, otherwise it might result in information leakage on test set and it neglects the purpose of testing dataset.

* Feature scaling can be done using Standardization (everything converted between -3 to +3) and Normalization (-1 to +1)

* Use Normalization is used when data is normally distributed
* Use Standardization is a universal technique and can be used even if data is not normally distributed

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**11. Initializing Artificial Neural Network**

In [49]:
ann = tf.keras.models.Sequential()

**12. Creating Hidden Layers**

In [40]:
#Create First Hidden Layers
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [99]:
#Create Second Hidden Layers
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

**13. Creating Output Layer**

In [100]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

**14. Compiling Artificial Neural Network**

In [103]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

**15.Fitting Artificial Neural Network**

In [104]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
99/99 [==============================] - 2s 3ms/step - loss: 0.6683 - accuracy: 0.6536
Epoch 2/100
99/99 [==============================] - 0s 3ms/step - loss: 0.4451 - accuracy: 0.8647
Epoch 3/100
99/99 [==============================] - 0s 3ms/step - loss: 0.3403 - accuracy: 0.8862
Epoch 4/100
99/99 [==============================] - 0s 3ms/step - loss: 0.3044 - accuracy: 0.8881
Epoch 5/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2839 - accuracy: 0.8891
Epoch 6/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2692 - accuracy: 0.8897
Epoch 7/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2583 - accuracy: 0.8913
Epoch 8/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2497 - accuracy: 0.8944
Epoch 9/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2424 - accuracy: 0.8966
Epoch 10/100
99/99 [==============================] - 0s 3ms/step - loss: 0.2367 - accuracy: 0.8966
Epoch 11/

**16. Save your created neural network**

In [ ]:
ann.save("ANN.h5")